### ISSUE TITLE
Error staking: Please collect your reward before otherwise using the program.

### ISSUE THREAD

**Issue by ncavet** [project-serum/stake#11]
This message appears when trying to stake locked tokens or unstake unlocked tokens:

Error staking: Please collect your reward before otherwise using the program.

Note: All rewards appear to have been collected via the GUI

**Comment by armaniferrante** [comment]
This should be fixed. Can you check the rewards tab again? If not would you like to share  your stake address? Feel free to message me in discord.

**Comment by armaniferrante** [comment]
I believe this has been resolved via Discord. Closing.
